### ISSUE TITLE
Galleries - NullPointerException

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#172]
I clicked on one of the images in 'Past Exhibitions' in the MOA gallery and got a null pointer exception:

```
java.lang.NullPointerException
    at edu.byu.support.utils.BitmapUtils.compressBitmapToByteArray(BitmapUtils.java:95)
    at edu.byu.suite.features.galleries.model.ArtworkResponseWrapper$Artwork.writeToParcel(ArtworkResponseWrapper.java:96)
    at android.os.Parcel.writeParcelable(Parcel.java:1285)
    ...
    at edu.byu.suite.features.galleries.controller.AlbumActivity$ImageAdapter.lambda$-edu_byu_suite_features_galleries_controller_AlbumActivity$ImageAdapter_lambda$1(AlbumActivity.java:129)
    at edu.byu.suite.features.galleries.controller.-$Lambda$261.$m$0(Unknown Source)
    at edu.byu.suite.features.galleries.controller.-$Lambda$261.onClick(Unknown Source)
```

**Comment by coreywoodfield** [comment]
I just got this bug again, and it seems to occur when I try to click on one of the thumbnails before the image is loaded. We should make the thumbnails not clickable until they're ready

**Comment by coreywoodfield** [comment]
It looks like it actually happens if I open any image before all of them are loaded. We should either make them not clickable until they're all loaded, or make the click listener set a flag to open the image when they're all done being loaded
