### ISSUE TITLE
MyNextClass crashing

### ISSUE THREAD

**Issue by romrell4** [byu-oit-appdev/android-byu-suite-v2#217]
Crashes whenever I open it (romrell4)

**Comment by romrell4** [comment]
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2.5 at line 1 column 1399 path $.WeeklySchedService.response.schedule_table[2].credit_hours
                                                              at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:245)
                                                              at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                              at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                                                              at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                                                              at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                              at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
                                                              at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                                                              at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                                              at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                              at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
                                                              at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                              at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.lang.NumberFormatException: Expected an int but was 2.5 at line 1 column 1399 path $.WeeklySchedService.response.schedule_table[2].credit_hours
                                                              at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1196)
                                                              at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243)
                                                              at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
                                                              at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
                                                              at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
                                                              at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
                                                              at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37) 
                                                              at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25) 
                                                              at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117) 
                                                              at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211) 
                                                              at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106) 
                                                              at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133) 
                                                              at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                              at java.lang.Thread.run(Thread.java:818) 
02-17 16:34:07.042 8185-8208/edu.byu.suite D/OpenGLRenderer: endAllStagingAnimators on 0x92860900 (RippleDrawable) with handle 0x93065160
02-17 16:34:07.442 8185-8185/edu.byu.suite E/WindowManager: android.view.WindowLeaked: Activity edu.byu.suite.features.myNextClass.controller.MyNextClassMainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3b4ac22d V.E..... R......D 0,0-684,232} that was originally added here
                                                                at android.view.ViewRootImpl.<init>(ViewRootImpl.java:375)
                                                                at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                                at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                at android.app.Dialog.show(Dialog.java:298)
                                                                at android.app.ProgressDialog.show(ProgressDialog.java:116)
                                                                at android.app.ProgressDialog.show(ProgressDialog.java:104)
                                                                at edu.byu.support.activity.ByuActivity.showProgressDialog(ByuActivity.java:110)
                                                                at edu.byu.support.activity.ByuActivity.showProgressDialog(ByuActivity.java:105)
                                                                at edu.byu.support.activity.ByuActivity.showProgressDialog(ByuActivity.java:97)
                                                                at edu.byu.suite.features.myNextClass.controller.MyNextClassMainActivity.loadAllData(MyNextClassMainActivity.java:103)
                                                                at edu.byu.suite.features.myNextClass.controller.MyNextClassMainActivity.onCreate(MyNextClassMainActivity.java:81)
                                                                at android.app.Activity.performCreate(Activity.java:6010)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by poolguy** [comment]
#232
