### ISSUE TITLE
No activity found to handle implicit intent

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#333]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=plugins/Upload/fileDownload.php?fileId=f2ded7bb-KMQu-rY66-1ZxL-GR664a3e6f32 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1872)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1568)
	at android.app.Activity.startActivityForResult(Activity.java:3755)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(Unknown Source)
	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivityForResult(Activity.java:3716)
	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivity(Activity.java:4036)
	at android.app.Activity.startActivity(Activity.java:3998)
	at android.text.style.URLSpan.onClick(URLSpan.java:62)
	at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
	at android.widget.TextView.onTouchEvent(TextView.java:7996)
	at android.view.View.dispatchTouchEvent(View.java:8476)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
	at android.view.View.dispatchPointerEvent(View.java:8671)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
```

**Comment by romrell4** [comment]
App Version: 107
Android Version: 5.1
Device: Moto G (1st Gen)
Reported: March 15th, 2017 at 10:00 AM
