### ISSUE TITLE
StringUtils.fromHtml can give an indexOutOfBoundsException

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#334]
```
java.lang.StringIndexOutOfBoundsException
    at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:59)
    at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:964)
    at edu.byu.support.utils.StringUtils.trim(Unknown Source)
    at edu.byu.support.utils.StringUtils.fromHtml(Unknown Source)
    at edu.byu.suite.features.learningSuite.model.Assignment.getDetailText(Unknown Source)
    at edu.byu.suite.features.learningSuite.fragment.AssignmentsFragment.-edu_byu_suite_features_learningSuite_fragment_AssignmentsFragment-mthref-1(Unknown Source)
    at edu.byu.suite.features.learningSuite.fragment.-$Lambda$43.$m$0(Unknown Source)
    at edu.byu.suite.features.learningSuite.fragment.-$Lambda$43.getText(Unknown Source)
    at edu.byu.support.defaults.DefaultViewHolder.bind(Unknown Source)
    at edu.byu.support.adapter.ByuRecyclerAdapter.onBindViewHolder(Unknown Source)
    at edu.byu.support.adapter.ByuRecyclerAdapter.onBindViewHolder(Unknown Source)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(Unknown Source)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(Unknown Source)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(Unknown Source)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source)
    at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(Unknown Source)
    at android.support.v7.widget.GapWorker.flushTaskWithDeadline(Unknown Source)
    at android.support.v7.widget.GapWorker.flushTasksWithDeadline(Unknown Source)
    at android.support.v7.widget.GapWorker.prefetch(Unknown Source)
    at android.support.v7.widget.GapWorker.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5525)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by romrell4** [comment]
App Version: 107
Android Version: 6.0
Device: LG G4
Reported: March 14th, 2017 at 12:54 AM
User Messages: "crashed"

**Comment by romrell4** [comment]
java.lang.StringIndexOutOfBoundsException
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:60)
	at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1139)
	at edu.byu.support.utils.StringUtils.trim(Unknown Source)
	at edu.byu.support.utils.StringUtils.fromHtml(Unknown Source)
	at edu.byu.suite.features.learningSuite.model.CalendarItem.getText(Unknown Source)
	at edu.byu.suite.features.learningSuite.fragment.CalendarFragment.lambda$-edu_byu_suite_features_learningSuite_fragment_CalendarFragment_lambda$1(Unknown Source)
	at edu.byu.suite.features.learningSuite.fragment.-$Lambda$44.$m$0(Unknown Source)
	at edu.byu.suite.features.learningSuite.fragment.-$Lambda$44.getText(Unknown Source)
	at edu.byu.support.defaults.DefaultViewHolder.bind(Unknown Source)
	at edu.byu.support.adapter.ByuRecyclerAdapter.onBindViewHolder(Unknown Source)
	at edu.byu.support.adapter.ByuRecyclerAdapter.onBindViewHolder(Unknown Source)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(Unknown Source)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(Unknown Source)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(Unknown Source)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.fill(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(Unknown Source)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source)
	at android.support.v7.widget.RecyclerView.dispatchLayout(Unknown Source)
	at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:818)
	at android.view.View.layout(View.java:18793)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2615)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2331)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:638)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
