### ISSUE TITLE
AuthToken RuntimeException

### ISSUE THREAD

**Issue by romrell4** [byu-oit-appdev/android-byu-suite-v2#338]
java.lang.RuntimeException: Error getting authtoken of type 'bearer' for account 'cblack98'
	at edu.byu.support.login.authentication.AuthTokenFactory.getToken(Unknown Source)
	at edu.byu.support.login.authentication.AuthTokenFactory.getBearerToken(Unknown Source)
	at edu.byu.support.login.authentication.AuthTokenFactory.getBearerTokenAuthHeader(Unknown Source)
	at edu.byu.support.retrofit.ByuApiGenerator$PublicBearerTokenInterceptor.intercept(Unknown Source)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(Unknown Source)
	at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
	at okhttp3.RealCall.access$100(Unknown Source)
	at okhttp3.RealCall$AsyncCall.execute(Unknown Source)
	at okhttp3.internal.NamedRunnable.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by romrell4** [comment]
java.lang.RuntimeException: Error getting authtoken of type 'bearer' for account 'claws121'
	at edu.byu.support.login.authentication.AuthTokenFactory.getToken(Unknown Source)
	at edu.byu.support.login.authentication.AuthTokenFactory.getBearerToken(Unknown Source)
	at edu.byu.support.login.authentication.AuthTokenFactory.getBearerTokenAuthHeader(Unknown Source)
	at edu.byu.support.retrofit.ByuApiGenerator$BearerTokenInterceptor.intercept(Unknown Source)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(Unknown Source)
	at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
	at okhttp3.RealCall.access$100(Unknown Source)
	at okhttp3.RealCall$AsyncCall.execute(Unknown Source)
	at okhttp3.internal.NamedRunnable.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
