### ISSUE TITLE
Cougar Cash has crashed every time I've used it to add funds

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#343]
Funds have been added successfully, but the app crashed

**Comment by coreywoodfield** [comment]
I just tested it in prod and got the following: 
```
03-17 11:51:24.669 26701-27644/edu.byu.suite D/OkHttp: --> PUT https://api.byu.edu/domains/cougar-cash/v1.1/payment/3067257 http/1.1
03-17 11:51:24.669 26701-27644/edu.byu.suite D/OkHttp: Content-Type: application/json
03-17 11:51:24.669 26701-27644/edu.byu.suite D/OkHttp: Content-Length: 70
03-17 11:51:24.669 26701-27644/edu.byu.suite D/OkHttp: {"payment_type_id":"c210d183-c1d4-4ec1-91af-f478543ff994BANK_ACCOUNT"}
03-17 11:51:24.669 26701-27644/edu.byu.suite D/OkHttp: --> END PUT (70-byte body)
03-17 11:51:24.709 26701-26701/edu.byu.suite D/ProgressBar: updateDrawableBounds: left = 0
03-17 11:51:24.709 26701-26701/edu.byu.suite D/ProgressBar: updateDrawableBounds: top = 0
03-17 11:51:24.709 26701-26701/edu.byu.suite D/ProgressBar: updateDrawableBounds: right = 96
03-17 11:51:24.709 26701-26701/edu.byu.suite D/ProgressBar: updateDrawableBounds: bottom = 96
03-17 11:51:34.739 26701-27644/edu.byu.suite D/OkHttp: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
03-17 11:51:34.819 26701-26701/edu.byu.suite D/dalvikvm: GC_FOR_ALLOC freed 5890K, 39% free 12432K/20252K, paused 70ms, total 70ms
03-17 11:51:34.819 26701-26701/edu.byu.suite E/ByuCallback: onFailure: 
                                                            java.net.SocketTimeoutException: timeout
                                                                at okio.Okio$3.newTimeoutException(Okio.java:212)
                                                                at okio.AsyncTimeout.exit(AsyncTimeout.java:277)
                                                                at okio.AsyncTimeout$2.read(AsyncTimeout.java:244)
                                                                at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
                                                                at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
                                                                at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
                                                                at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                                                                at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                at edu.byu.support.retrofit.ByuApiGenerator$BearerTokenInterceptor.intercept(ByuApiGenerator.java:76)
                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:841)
03-17 11:51:34.819 26701-26701/edu.byu.suite D/AndroidRuntime: Shutting down VM
03-17 11:51:34.819 26701-26701/edu.byu.suite W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41b39da0)
03-17 11:51:34.819 26701-26701/edu.byu.suite E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: edu.byu.suite, PID: 26701
                                                               java.lang.NullPointerException
                                                                   at edu.byu.suite.features.cougarCash.controller.PaymentReviewActivity$2.onFailure(PaymentReviewActivity.java:116)
                                                                   at edu.byu.support.retrofit.ByuCallback.retryCall(ByuCallback.java:84)
                                                                   at edu.byu.support.retrofit.ByuCallback.onFailure(ByuCallback.java:96)
                                                                   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:77)
                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:146)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5487)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                   at dalvik.system.NativeStart.main(Native Method)
```
(So I got a timeout, which caused onFailure to be called. onFailure assumed we got a response back, but that's not always the case. That caused a null pointer exception)
I fixed the null pointer exception, but I don't think the timeout is on our end. That also explains why it didn't fail in sandbox, cus it's a lot easier to not get a timeout in sandbox
